export {
  analyzeBehavioralSamples,
  aggregateSuspicionScore,
  buildBehavioralSignals,
  createBehavioralClientDetector,
  hasClickWithoutMouseMovement,
  hasLinearMouseMovement,
  hasLinearScroll,
  hasLinearTyping,
  hasNoMouseActivity,
  hasSyntheticEvents,
  hasTeleportMouse,
  resolveConfidence,
} from "./behavioral/index.js";
export {
  aggregateInstantSuspicionScore,
  buildInstantSignals,
  checkShaderF16Support,
  detectInstantClient,
  detectInstantClientAsync,
  isHuman,
  isHumanAsync,
  isAutomationArtifacts,
  isChromeDriver,
  isChromiumBrowser,
  isEmptyPlugins,
  isLanguageInconsistent,
  isMissingChromeObject,
  isPlaywright,
  isPluginMimeTypeInconsistent,
  isPuppeteer,
  isSoftwareRenderer,
  isSuspiciousWebDriverDescriptor,
  isSuspiciousWindowDimensions,
  isUserAgentDataMismatch,
  resolveInstantConfidence,
} from "./detectInstantClient.js";
export type {
  AutomationAssessment,
  AutomationConfidence,
  AutomationKind,
} from "./automation.js";
export type {
  BehavioralClientDetector,
  BehavioralClientResult,
  BehavioralDetectorOptions,
  BehavioralSampleCounts,
  BehavioralSamples,
  BehavioralSignal,
  ClickSample,
  ConfidenceLevel,
  KeySample,
  MouseSample,
  ScrollSample,
  TouchSample,
} from "./behavioral/types.js";
export type {
  ExtendedDocument,
  ExtendedNavigator,
  ExtendedWindow,
  InstantClientAsyncResult,
  InstantClientResult,
  InstantConfidenceLevel,
  InstantDetectorOptions,
  InstantSignal,
} from "./types.js";
export { VERSION } from "./version.js";
