export {
  analyzeBehavioralSamples,
  aggregateSuspicionScore,
  buildBehavioralSignals,
  createBehavioralClientDetector,
  hasClickWithoutMouseMovement,
  hasLinearMouseMovement,
  hasLinearScroll,
  hasLinearTyping,
  hasNoMouseActivity,
  hasSyntheticEvents,
  hasTeleportMouse,
  resolveConfidence,
} from "./behavioral/index.js";
export {
  aggregateInstantSuspicionScore,
  buildInstantSignals,
  checkShaderF16Support,
  detectInstantClient,
  detectInstantClientAsync,
  isHuman,
  isHumanAsync,
  isAutomationArtifacts,
  isChromeDriver,
  isChromiumBrowser,
  isEmptyPlugins,
  isLanguageInconsistent,
  isMissingChromeObject,
  isPlaywright,
  isPluginMimeTypeInconsistent,
  isPuppeteer,
  isSoftwareRenderer,
  isSuspiciousWebDriverDescriptor,
  isSuspiciousWindowDimensions,
  isUserAgentDataMismatch,
  resolveInstantConfidence,
} from "./detectInstantClient.js";
export {
  aggregateServerSuspicionScore,
  buildServerSignals,
  createIpListChecker,
  detectServerClient,
  detectServerClientAsync,
  enrichServerContext,
  findTlsFingerprintEntry,
  getDefaultIpDataDir,
  getIpListChecker,
  getTimezoneOffsetMinutes,
  getUserAgentFamily,
  isAcceptLanguageGeoMismatch,
  isBrowserLikeUserAgent,
  isClientHintsMismatch,
  isDatacenterBrowserMismatch,
  isKnownSuspiciousTlsFingerprint,
  isMissingTlsFingerprint,
  isMissingBrowserHeaders,
  isScriptingUserAgent,
  isTimezoneMismatch,
  isTlsUserAgentMismatch,
  isValidJa3Hash,
  KNOWN_SUSPICIOUS_TLS_FINGERPRINTS,
  lookupClientIpGeo,
  normalizeTlsFingerprint,
  parseIp,
  preloadIpLists,
  resetIpListCheckerCache,
  resolveServerConfidence,
} from "./server/index.js";
export type {
  AutomationAssessment,
  AutomationConfidence,
  AutomationKind,
} from "./automation.js";
export type {
  BehavioralClientDetector,
  BehavioralClientResult,
  BehavioralDetectorOptions,
  BehavioralSampleCounts,
  BehavioralSamples,
  BehavioralSignal,
  ClickSample,
  ConfidenceLevel,
  KeySample,
  MouseSample,
  ScrollSample,
  TouchSample,
} from "./behavioral/types.js";
export type {
  EnrichedServerContext,
  IpGeoResult,
  IpListChecker,
  IpListMatchResult,
  ParsedIp,
  ServerClientContext,
  ServerClientResult,
  ServerConfidenceLevel,
  ServerDetectorOptions,
  ServerSignal,
  TlsFingerprintEntry,
  UserAgentFamily,
} from "./server/index.js";
export type {
  ExtendedDocument,
  ExtendedNavigator,
  ExtendedWindow,
  InstantClientAsyncResult,
  InstantClientResult,
  InstantConfidenceLevel,
  InstantDetectorOptions,
  InstantSignal,
} from "./types.js";
export { VERSION } from "./version.js";
